-- ROOT 아이템을 찾아 아이템 ID(ITEM_ID), 아이템 명(, ITEM_NAME)을 출력

SELECT A.ITEM_ID, A.ITEM_NAME
FROM ITEM_INFO A INNER JOIN ITEM_TREE B
ON A.ITEM_ID = B.ITEM_ID
-- IFNULL(B.PARENT_ITEM_ID, 
WHERE B.PARENT_ITEM_ID IS NULL
ORDER BY A.ITEM_ID