-- 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 출력
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*30*(100-D.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C 
ON H.CAR_ID = C.CAR_ID
JOIN (
    SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
) D
ON C.CAR_TYPE = D.CAR_TYPE
-- 자동차 종류가 '세단' 또는 'SUV', 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능, 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
WHERE C.CAR_TYPE IN ('세단','SUV') AND C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE < '2022-12-01' AND END_DATE > '2022-11-01'
)
GROUP BY C.CAR_ID
HAVING FEE>=500000 AND FEE<2000000 
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC

# C.DAILY_FEE*30*((100-CONVERT(SUBSTRING(D.DISCOUNT_RATE, -2)),UNSIGNED)/100)