-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE),2) as SCORE
FROM REST_INFO as I INNER JOIN REST_REVIEW as R
ON I.REST_ID = R.REST_ID
group by R.REST_ID
having SUBSTR(ADDRESS,1,2)='서울'
ORDER BY SCORE desc, FAVORITES desc