-- 사원별 성과금 정보를 출력
-- 사번, 성명, 평가 등급GRADE, 성과금BONUS을 조회
SELECT E.EMP_NO, E.EMP_NAME, 
(
    CASE
    WHEN AVG(G.SCORE) >= 96 THEN 'S'
    WHEN AVG(G.SCORE) >= 90 THEN 'A'
    WHEN AVG(G.SCORE) >= 80 THEN 'B'
    ELSE 'C'
    END
) AS GRADE,
E.SAL * (
    CASE
    WHEN AVG(G.SCORE) >= 96 THEN 0.2
    WHEN AVG(G.SCORE) >= 90 THEN 0.15
    WHEN AVG(G.SCORE) >= 80 THEN 0.1
    ELSE 0
    END
) AS BONUS
FROM HR_EMPLOYEES E INNER JOIN HR_GRADE G
ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO, G.YEAR
ORDER BY E.EMP_NO