-- 코드를 입력하세요
SELECT I.ANIMAL_ID , I.NAME
FROM ANIMAL_INS I INNER JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
-- 보호 시작일보다 입양일이 더 빠른 동물
WHERE I.DATETIME > O.DATETIME
-- 보호 시작일이 빠른 순으로 조회
ORDER BY I.DATETIME