-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차들에 대해서
WHERE DATE_FORMAT(START_DATE,'%Y-%m') between '2022-08' and '2022-10'
AND CAR_ID IN ( SELECT CAR_ID 
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
               WHERE DATE_FORMAT(START_DATE,'%Y-%m') between '2022-08' and '2022-10' 
               GROUP BY CAR_ID 
               HAVING COUNT(HISTORY_ID)>4 )
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH(START_DATE), CAR_ID DESC