# 분화된 연도별 대장균 크기의 편차
# = 분화된 연도별 가장 큰 대장균의 크기 - 각 대장균의 크기

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
(SELECT MAX(SIZE_OF_COLONY)
FROM ECOLI_DATA B
WHERE YEAR(A.DIFFERENTIATION_DATE) = YEAR(B.DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV
, ID
FROM ECOLI_DATA A

ORDER BY YEAR, YEAR_DEV

