SELECT YEAR(DIFFERENTIATION_DATE) YEAR, (SELECT MAX(B.SIZE_OF_COLONY)
                                         FROM ECOLI_DATA B
                                         WHERE YEAR(A.DIFFERENTIATION_DATE) = YEAR(B.DIFFERENTIATION_DATE)) - A.SIZE_OF_COLONY YEAR_DEV, ID
FROM ECOLI_DATA A
ORDER BY YEAR, YEAR_DEV