# 물고기 종류 별로 가장 큰 물고기의 ID, 물고기 이름, 길이
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH = (SELECT MAX(LENGTH)
                 FROM FISH_INFO
                 WHERE FISH_TYPE = I.FISH_TYPE)
ORDER BY I.ID              