# 물고기 종류 별로 가장 큰 물고기의 ID, 물고기 이름, 길이
SELECT A.ID AS ID, B.FISH_NAME AS FISH_NAME, A.LENGTH AS LENGTH
FROM FISH_INFO as A INNER JOIN FISH_NAME_INFO as B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO
    WHERE FISH_TYPE = A.FISH_TYPE
)
ORDER BY A.ID