SELECT CASE 
        WHEN SUM(CASE WHEN A.CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0 AND 
            SUM(CASE WHEN A.NAME = 'Python' THEN 1 ELSE 0 END) > 0 THEN 'A'
        WHEN SUM(CASE WHEN A.NAME = 'C#' THEN 1 ELSE 0 END) > 0 THEN 'B'
        WHEN SUM(CASE WHEN A.CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0 THEN 'C'
        END AS GRADE, b.ID, b.EMAIL
FROM SKILLCODES AS A LEFT OUTER JOIN DEVELOPERS AS B
-- SKILL_CODE가 400 (=b'110010000')이라면, 
-- SKILLCODES 테이블에서 CODE가 256 (=b'100000000'), 128 (=b'10000000'), 16 (=b'10000') 에 해당하는 스킬을 가졌다는 것을 연산하는 방법
ON A.CODE & B.SKILL_CODE
GROUP BY B.ID, B.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID

